package il.ac.tau.cs.sw1.ex9.starfleet;

import java.util.Objects;

public class CrewWoman implements CrewMember
{
	String name;
	int age;
	int getYearsInService;

	
	public CrewWoman(int age, int yearsInService, String name)
	{
		this.name = name;
		this.age = age;
		this.getYearsInService = yearsInService;
	}


	public String getName() 
	{
		return this.name;
	}


	public int getAge() 
	{
		return this.age;
	}


	public int getYearsInService() 
	{
		return this.getYearsInService;
	}

	//Generated by: Source --> generate hashCode() and equals()...
	@Override
	public int hashCode()
	{
		return Objects.hash(name);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CrewWoman other = (CrewWoman) obj;
		return Objects.equals(name, other.name);
	}	
}
