package il.ac.tau.cs.sw1.ex9.starfleet;

import java.util.Objects;
import java.util.Set;

abstract class mySpaceship implements Spaceship
{
	String name;
	int commissionYear;
	float maximalSpeed;
	int firePower;
	Set<? extends CrewMember> crewMembers;
	float annualMaintenanceCost;
	
	public mySpaceship(String name, int commissionYear, float maximalSpeed, Set<? extends CrewMember> crewMembers)
	{
		this.name = name;
		this.commissionYear = commissionYear;
		this.maximalSpeed = maximalSpeed;
		this.firePower = 10;
		this.crewMembers = crewMembers;		
		this.annualMaintenanceCost = 0;
	}


	/*
	public String getType()
	{
		return this.getClass().getSimpleName();
	}
	*/
	
	public String getName()
	{
		return this.name;
	}

	public int getCommissionYear()
	{
		return this.commissionYear;
	}

	public float getMaximalSpeed()
	{
		return this.maximalSpeed;
	}

	public int getFirePower()
	{
		return this.firePower;	
	}

	public Set<? extends CrewMember> getCrewMembers()
	{
		return this.crewMembers;
	}

	public int getAnnualMaintenanceCost()
	{
		return (int)this.annualMaintenanceCost;
	}
	
	public String toString()
	{
		return this.getClass().getSimpleName() + System.lineSeparator() 
				+ "\t" + "Name=" + this.getName() + System.lineSeparator() 
				+ "\t" + "CommissionYear=" + this.getCommissionYear() + System.lineSeparator() 
				+ "\t" + "MaximalSpeed=" + this.getMaximalSpeed() + System.lineSeparator() 
				+ "\t" + "FirePower=" + this.getFirePower() + System.lineSeparator() 
				+ "\t" + "CrewMembers=" + this.getCrewMembers().size() + System.lineSeparator() 
				+ "\t" + "AnnualMaintenanceCost=" + this.getAnnualMaintenanceCost();
	}

	//Generated by: Source --> generate hashCode() and equals()...
	@Override
	public int hashCode()
	{
		return Objects.hash(name);
	}


	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		mySpaceship other = (mySpaceship) obj;
		return Objects.equals(name, other.name);
	}	
}
